---
# tasks file for service_control
- name: Start the Service
  service:
    name: "{{ service_name }}"
    state: started
  when: service_action == "1"

- name: Stop the Service
  service:
    name: "{{ service_name }}"
    state: stopped
  when: service_action == "2"

- name: Restart the Service
  service:
    name: "{{ service_name }}"
    state: restarted
  when: service_action == "3"
